[tool.poetry]
name = "web-scraping-rastreio"
version = "0.1.0"
description = ""
authors = ["Nicolas <nicolas_evilasio@hotmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
selenium = "^4.27.1"
webdriver-manager = "^4.0.2"
playwright = "^1.49.1"
pandas = "^2.2.3"
requests = "^2.32.3"
redis = "^5.2.1"
deprecated = "^1.2.15"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
